apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: flomo-cronjob
  namespace: dev
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: flomo-cronjob
            image: curlimages/curl:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl -X GET http://${FLOMO_HOST}:${FLOMO_PORT}/app/algorithmCoding/repo/update?dashuaibi=zhu733756&token=${TOKEN};
            env:
            - name: "FLOMO_HOST"
              value: ""
            - name: "FLOMO_PORT"
              value: ""
            - name: "TOKEN"
              value: ""
          restartPolicy: OnFailure
