apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-codes
  namespace: dev
  labels:
    app: projects
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projects
  template:
    metadata:
      labels:
        app: projects
    spec:
      volumes:
      - name: repo
        hostPath:
          path: /gitRepo
      containers:
      - name: app-projects
        image: zhu733756/app-codes:latest
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5000
        env:
          - name: "FLOMO_USERNAME"
            value: ""
          - name: "FLOMO_PASSWORD"
            value: ""
          - name : "TOKEN"
            value: ""
          - name : "APPID"
            value: ""
          - name : "APPSECRET"
            value: ""
          - name: "AES_KEY"
            value: ""
        volumeMounts:
        - name: repo
          mountPath: /gitRepo
---
apiVersion: v1
kind: Service
metadata:
  name: app-codes
  namespace: dev
spec:
  selector:
    app: projects
  ports:
    - name: app-projects
      port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: 31001
  type: NodePort        
